<template>
  <div id="get-vw" style="position: absolute; height: 100%; overflow: hidden; text-align: center;">
    <div style="position: relative;">
      <div id="scale-me" style="display: inline-block; transform-origin: 0 0;">
        <img
          id="get-width"
          style="margin: 26px; opacity: .5; z-index: -1"
          src="~@/assets/worldmap.png">
        <div style="position: absolute; width: 100%; height: 100%; top: 0;">
          <div>
            <country
              country="afghanistan"
              top="851"
              left="1849"
              armies="500"
              topArmies="-30"
              leftArmies="-50"
              player=""
            ></country>
            <country
              country="alaska"
              top="698"
              left="238"
              armies="0"
              topArmies="-80"
              leftArmies="0"
              player=""
            ></country>
            <country
              country="alberta"
              top="781"
              left="450"
              armies="0"
              topArmies="-20"
              leftArmies="0"
              player=""
            ></country>
            <country
              country="argentina"
              top="1497"
              left="922"
              armies="0"
              topArmies="-50"
              leftArmies="-50"
              player=""
            ></country>
            <country
              country="brazile"
              top="1326"
              left="1036"
              armies="0"
              topArmies="-50"
              leftArmies="-40"
              player=""
            ></country>
            <country
              country="central-europe"
              top="844"
              left="1520"
              armies="0"
              topArmies="-50"
              leftArmies="-20"
              player=""
            ></country>
            <country
              country="china"
              top="908"
              left="2068"
              armies="0"
              topArmies="-50"
              leftArmies="-30"
              player=""
            ></country>
            <country
              country="east-africa"
              top="1166"
              left="1616"
              armies="0"
              topArmies="-50"
              leftArmies="-30"
              player=""
            ></country>
            <country
              country="east-australia"
              top="1392"
              left="2399"
              armies="0"
              topArmies="-70"
              leftArmies="-90"
              player=""
            ></country>
            <country
              country="eastern-usa"
              top="981"
              left="713"
              armies="0"
              topArmies="-60"
              leftArmies="-60"
              player=""
            ></country>
            <country
              country="egypt"
              top="1064"
              left="1524"
              armies="0"
              topArmies="-50"
              leftArmies="-30"
              player=""
            ></country>
            <country
              country="great-britany"
              top="824"
              left="1412"
              armies="0"
              topArmies="-70"
              leftArmies="-30"
              player=""
            ></country>
            <country
              country="greenland"
              top="509"
              left="725"
              armies="0"
              topArmies="-40"
              leftArmies="100"
              player=""
            ></country>
            <country
              country="india"
              top="988"
              left="1918"
              armies="0"
              topArmies="-50"
              leftArmies="-20"
              player=""
            ></country>
            <country
              country="indonesia"
              top="1136"
              left="2160"
              armies="0"
              topArmies="0"
              leftArmies="0"
              player=""
            ></country>
            <country
              country="island"
              top="757"
              left="1314"
              armies="0"
              topArmies="-100"
              leftArmies="10"
              player=""
            ></country>
            <country
              country="jakutzka"
              top="550"
              left="2135"
              armies="0"
              topArmies="-70"
              leftArmies="-70"
              player=""
            ></country>
            <country
              country="japan"
              top="889"
              left="2403"
              armies="0"
              topArmies="20"
              leftArmies="50"
              player=""
            ></country>
            <country
              country="kamchatka"
              top="621"
              left="2425"
              armies="0"
              topArmies="-40"
              leftArmies="-120"
              player=""
            ></country>
            <country
              country="kongo"
              top="1291"
              left="1565"
              armies="0"
              topArmies="-10"
              leftArmies="-90"
              player=""
            ></country>
            <country
              country="madagascar"
              top="1406"
              left="1800"
              armies="0"
              topArmies="0"
              leftArmies="0"
              player=""
            ></country>
            <country
              country="mexico"
              top="1056"
              left="636"
              armies="0"
              topArmies="-40"
              leftArmies="-120"
              player=""
            ></country>
            <country
              country="middle-east"
              top="1001"
              left="1675"
              armies="0"
              topArmies="0"
              leftArmies="0"
              player=""
            ></country>
            <country
              country="mongolia"
              top="820"
              left="2167"
              armies="0"
              topArmies="-80"
              leftArmies="0"
              player=""
            ></country>
            <country
              country="new-guinea"
              top="1320"
              left="2428"
              armies="0"
              topArmies="-90"
              leftArmies="-40"
              player=""
            ></country>
            <country
              country="north-africa"
              top="1027"
              left="1359"
              armies="0"
              topArmies="0"
              leftArmies="0"
              player=""
            ></country>
            <country
              country="northwest-teritory"
              top="569"
              left="428"
              armies="0"
              topArmies="0"
              leftArmies="0"
              player=""
            ></country>
            <country
              country="ontario"
              top="812"
              left="709"
              armies="0"
              topArmies="-50"
              leftArmies="-30"
              player=""
            ></country>
            <country
              country="peru"
              top="1318"
              left="923"
              armies="0"
              topArmies="0"
              leftArmies="-60"
              player=""
            ></country>
            <country
              country="quebec"
              top="801"
              left="865"
              armies="0"
              topArmies="-30"
              leftArmies="-50"
              player=""
            ></country>
            <country
              country="scandinavia"
              top="563"
              left="1483"
              armies="0"
              topArmies="-50"
              leftArmies="-80"
              player=""
            ></country>
            <country
              country="siam"
              top="1075"
              left="2132"
              armies="1000"
              topArmies="-60"
              leftArmies="-40"
              player=""
            ></country>
            <country
              country="siberia"
              top="614"
              left="2011"
              armies="0"
              topArmies="-100"
              leftArmies="-30"
              player=""
            ></country>
            <country
              country="south-africa"
              top="1357"
              left="1573"
              armies="0"
              topArmies="0"
              leftArmies="-50"
              player=""
            ></country>
            <country
              country="south-europe"
              top="908"
              left="1510"
              armies="0"
              topArmies="-40"
              leftArmies="0"
              player=""
            ></country>
            <country
              country="ucraine"
              top="540"
              left="1650"
              armies="0"
              topArmies="40"
              leftArmies="-50"
              player=""
            ></country>
            <country
              country="ural"
              top="668"
              left="1900"
              armies="0"
              topArmies="-60"
              leftArmies="-60"
              player=""
            ></country>
            <country
              country="utah"
              top="742"
              left="2145"
              armies="0"
              topArmies="-40"
              leftArmies="-30"
              player=""
            ></country>
            <country
              country="venezuela"
              top="1204"
              left="904"
              armies="0"
              topArmies="-80"
              leftArmies="-30"
              player=""
            ></country>
            <country
              country="west-australia"
              top="1398"
              left="2303"
              armies="0"
              topArmies="-20"
              leftArmies="-40"
              player=""
            ></country>
            <country
              country="west-europe"
              top="910"
              left="1421"
              armies="0"
              topArmies="-30"
              leftArmies="-120"
              player=""
            ></country>
            <country
              country="western-usa"
              top="947"
              left="591"
              armies="0"
              topArmies="-30"
              leftArmies="-80"
              player=""
            ></country>
          </div>
        </div>
      </div>
    </div>
  </div>
</template>

<script>
  import Country from './Country'
  import jquery from 'jquery'

  export default {
    components: {Country},
    data () {
      return {
        diff: window.outerHeight / window.outerWidth
      }
    },
    mounted () {
      this.getWindowWidth()
    },
    created () {
      let scope = this
      jquery(window).resize(function () {
        let diffNew = window.outerHeight / window.outerWidth
        if (scope.diff !== diffNew) {
          scope.getWindowWidth()
          scope.diff = diffNew
        }
      })
      this.getWindowWidth()
    },
    methods: {
      getWindowWidth () {
        setTimeout(function () {
          jquery('#scale-me').css({
            zoom: (jquery('#get-vw').height() / jquery('#get-width').height()) + 0.08
          })
          jquery('#get-vw').css({
            marginTop: '-150px',
            marginLeft: ((jquery('#board').width() - jquery('#get-vw').width()) / 2) + 'px'
          })
        }, 500)
      }
    }
  }
</script>

<style scoped>
</style>
